trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.14.3'
  displayName: 'Install Go 1.14.3'

- script: |
    go mod download
  displayName: 'Download dependencies'

- script: |
    go test -v ./...
  displayName: 'Run tests'
